// ── SUPABASE CONFIG ──────────────────────────────────────
// 1. Go to supabase.com → your project → Settings → API
// 2. Paste your Project URL and anon key below
const SUPABASE_URL  = 'https://gvxdabtmksxhujeytofv.supabase.co';
const SUPABASE_KEY  = 'sb_publishable_eERuVHBjTdhkIxpWvCX62A_3bMoXgAn';
const SUPABASE_ANON = SUPABASE_KEY;

const sb = (typeof supabase !== 'undefined')
  ? supabase.createClient(SUPABASE_URL, SUPABASE_KEY)
  : null;

let currentUser = null;

// Auth state listener — fires on page load and on login/logout
if(sb){
  sb.auth.onAuthStateChange(async (event, session) => {
    currentUser = session?.user ?? null;
    if(currentUser && window.JukeOnboarding) JukeOnboarding.start('athlete');
    if(typeof _updateAuthUI === 'function') _updateAuthUI();
    if(currentUser && event === 'SIGNED_IN' && typeof _syncFromCloud === 'function'){
      await _syncFromCloud();
      if(typeof showToast==='function') showToast('Board synced to cloud ✓');
      // Refresh board sync notice now that user is signed in
      if(typeof _renderBoardCols==='function') _renderBoardCols();
    }
    if(currentUser && event === 'INITIAL_SESSION' && typeof initMessaging === 'function') await initMessaging();
  });
}

// ── SCHOOL DOMAINS ────────────────────────────────────────
// Maps display school names → clearbit logo domains.
// Consumed by ui.js (fetchSchoolLogo), pipeline.js, program-finder.js.
const SCHOOL_DOMAINS={
  "Adelphi":"adelphi.edu",
  "Agnes Scott":"agnesscott.edu",
  "Alabama State":"alasu.edu",
  "Albany":"albany.edu",
  "Albright":"albright.edu",
  "Alexandria Tech":"alextech.edu",
  "Allegheny":"allegheny.edu",
  "Andrew":"andewcollege.edu",
  "Arizona":"arizona.edu",
  "Arizona Christian":"arizonachristian.edu",
  "Arizona State":"asu.edu",
  "Atlantis":"atlantisuniversity.edu",
  "Augsburg":"augsburg.edu",
  "Augustana":"augie.edu",
  "Aurora":"aurora.edu",
  "Avila":"avila.edu",
  "Azusa Pacific":"apu.edu",
  "Baker":"bakeru.edu",
  "Baldwin Wallace":"bw.edu",
  "Barber-Scotia":"barber-scotia.edu",
  "Barry":"barry.edu",
  "Barton":"barton.edu",
  "Beloit":"beloit.edu",
  "Benedictine":"ben.edu",
  "Benedictine Mesa":"ben.edu",
  "Bethany":"bethanywv.edu",
  "Bethel":"bethelks.edu",
  "Bishop State CC":"bishop.edu",
  "Blackburn":"blackburn.edu",
  "Bluefield State":"bluefieldstate.edu",
  "Boise State":"boisestate.edu",
  "Bowdoin":"bowdoin.edu",
  "Bowie State":"bowiestate.edu",
  "Bowling Green":"bgsu.edu",
  "Bradley":"bradley.edu",
  "Brewton-Parker":"bpc.edu",
  "Bridgeport":"bridgeport.edu",
  "Bridgewater":"bridgewater.edu",
  "Bryant & Stratton (Albany)":"bryantstratton.edu",
  "Bryant & Stratton (Buffalo)":"bryantstratton.edu",
  "Bryant & Stratton (Syracuse)":"bryantstratton.edu",
  "Bryant & Stratton (WI)":"bryantstratton.edu",
  "Bucks CC":"bucks.edu",
  "Buffalo":"buffalo.edu",
  "Cabrillo CC":"cabrillo.edu",
  "Cairn":"cairn.edu",
  "Cal":"berkeley.edu",
  "Cal Baptist":"calbaptist.edu",
  "Cal Lutheran":"callutheran.edu",
  "Cal Poly":"calpoly.edu",
  "Cal Poly Pomona":"cpp.edu",
  "Caldwell":"caldwell.edu",
  "Calhoun CC":"calhoun.edu",
  "Calumet":"calumet.edu",
  "Camden":"camdencc.edu",
  "Campbellsville":"campbellsville.edu",
  "Carson-Newman":"cn.edu",
  "Cedar Crest":"cedarcrest.edu",
  "Centenary":"centenary.edu",
  "Central Alabama CC":"cacc.edu",
  "Charlotte":"charlotte.edu",
  "Chatham":"chatham.edu",
  "Chestnut Hill":"chc.edu",
  "Chowan":"chowan.edu",
  "Citrus":"citruscollege.edu",
  "Claflin":"claflin.edu",
  "Claremont Colleges":"claremont.edu",
  "Clemson":"clemson.edu",
  "Coastal Carolina":"coastal.edu",
  "Colorado":"colorado.edu",
  "Columbus State":"columbusstate.edu",
  "Concordia":"concordia.edu",
  "Concordia Moorhead":"cord.edu",
  "Cornell":"cornellcollege.edu",
  "Cottey":"cottey.edu",
  "Cumberland":"cumberland.edu",
  "Cypress":"cypresscollege.edu",
  "D'Youville":"dyouville.edu",
  "Daemen":"daemen.edu",
  "Davenport":"davenport.edu",
  "Daytona State":"daytonastate.edu",
  "Dean":"dean.edu",
  "Defiance":"defiance.edu",
  "Delaware":"udel.edu",
  "Delaware State":"desu.edu",
  "Denver":"du.edu",
  "Diablo Valley":"dvc.edu",
  "Dominican":"dc.edu",
  "DuPage":"cod.edu",
  "Duke":"duke.edu",
  "East Los Angeles":"elac.edu",
  "East Texas Baptist":"etbu.edu",
  "Eastern Connecticut State":"easternct.edu",
  "Eastern Kentucky":"eku.edu",
  "Eastern Michigan":"emich.edu",
  "Eastern University":"eastern.edu",
  "Edward Waters":"ewc.edu",
  "El Camino":"elcamino.edu",
  "Elmira":"elmira.edu",
  "Emmanuel":"ec.edu",
  "Enterprise State CC":"escc.edu",
  "Erskine":"erskine.edu",
  "Eureka":"eureka.edu",
  "Fairleigh Dickinson":"fdu.edu",
  "Fayetteville State":"uncfsu.edu",
  "Ferrum":"ferrum.edu",
  "Five Towns":"ftc.edu",
  "Florida":"ufl.edu",
  "Florida A&M":"famu.edu",
  "Florida Atlantic":"fau.edu",
  "Florida Gateway":"fgc.edu",
  "Florida Gulf Coast":"fgcu.edu",
  "Florida International":"fiu.edu",
  "Florida Memorial":"fmuniv.edu",
  "Florida State":"fsu.edu",
  "Fort Lauderdale":"citc.edu",
  "Franciscan":"franciscan.edu",
  "Freed-Hardeman":"fhu.edu",
  "Gallaudet":"gallaudet.edu",
  "Georgia":"uga.edu",
  "Georgia College":"gcsu.edu",
  "Georgia Highlands":"highlands.edu",
  "Georgia Southern":"georgiasouthern.edu",
  "Georgia Tech":"gatech.edu",
  "Golden West":"goldenwestcollege.edu",
  "Goldey-Beacom":"gbc.edu",
  "Grace":"graceco.edu",
  "Graceland":"graceland.edu",
  "Grand Canyon":"gcu.edu",
  "Greenville":"greenville.edu",
  "Grossmont":"grossmont.edu",
  "Guilford":"guilford.edu",
  "Gustavus Adolphus":"gustavus.edu",
  "Harcum":"harcum.edu",
  "Hardin-Simmons":"hsutx.edu",
  "Harford CC":"harford.edu",
  "Harrisburg CC":"hacc.edu",
  "Hartwick":"hartwick.edu",
  "Harvard":"harvard.edu",
  "Hastings":"hastings.edu",
  "Hawaii Pacific":"hpu.edu",
  "Heidelberg":"heidelberg.edu",
  "Hendrix":"hendrix.edu",
  "Hesston":"hesston.edu",
  "High Point":"highpoint.edu",
  "Hocking":"hocking.edu",
  "Hollins":"hollins.edu",
  "Holy Family":"holyfamily.edu",
  "Hope International":"hiu.edu",
  "Howard":"howard.edu",
  "Howard CC":"howardcc.edu",
  "Howard Payne":"hputx.edu",
  "Huntingdon":"huntingdon.edu",
  "Illinois College":"ic.edu",
  "Illinois Springfield":"uis.edu",
  "Illinois Wesleyan":"iwu.edu",
  "Immaculata":"immaculata.edu",
  "Indiana":"indiana.edu",
  "Indiana Wesleyan":"indwes.edu",
  "Iona":"iona.edu",
  "Irvine Valley":"ivc.edu",
  "Jackson State CC":"jscc.edu",
  "Jacksonville":"ju.edu",
  "John Carroll":"jcu.edu",
  "John Melvin CC":"johnmelvin.edu",
  "Johnson C. Smith":"jcsu.edu",
  "Kansas Christian":"kansaschristian.edu",
  "Kansas Wesleyan":"kwu.edu",
  "Kean":"kean.edu",
  "Keiser":"keiseruniversity.edu",
  "Kennesaw State":"kennesaw.edu",
  "Keystone":"keystone.edu",
  "King":"king.edu",
  "Knox":"knox.edu",
  "LAHC":"lahc.edu",
  "La Sierra":"lasierra.edu",
  "LaGrange":"lagrange.edu",
  "Lakeland":"lakeland.edu",
  "Lancaster Bible":"lbc.edu",
  "Lees-McRae":"lmc.edu",
  "Lewis":"lewisu.edu",
  "Life":"life.edu",
  "Lindsey Wilson":"lindsey.edu",
  "Livingstone":"livingstone.edu",
  "Long Beach State":"csulb.edu",
  "Long Island":"liu.edu",
  "Lurleen B. Wallace CC":"lbwcc.edu",
  "Maharishi":"miu.edu",
  "Manhattan":"manhattan.edu",
  "Manor":"manor.edu",
  "Marian":"marianuniversity.edu",
  "Mars Hill":"mhc.edu",
  "Mary Hardin-Baylor":"umhb.edu",
  "Maryland":"umd.edu",
  "Marymount":"marymount.edu",
  "Marywood":"marywood.edu",
  "Mayville State":"mayvillestate.edu",
  "McMurry":"mcm.edu",
  "McPherson":"mcpherson.edu",
  "Menlo":"menlo.edu",
  "Mercy":"mercy.edu",
  "Mercyhurst":"mercyhurst.edu",
  "Meredith":"meredith.edu",
  "Michigan":"umich.edu",
  "Midland":"midlandu.edu",
  "Midway":"midway.edu",
  "Milligan":"milligan.edu",
  "Millikin":"millikin.edu",
  "Millsaps":"millsaps.edu",
  "Minnesota State Mankato":"mnsu.edu",
  "MiraCosta":"miracosta.edu",
  "Mississippi Valley State":"mvsu.edu",
  "Missouri Baptist":"mobap.edu",
  "Missouri Southern State":"mssu.edu",
  "Missouri Valley":"moval.edu",
  "Modesto JC":"mjc.edu",
  "Montana":"umt.edu",
  "Montana State":"montana.edu",
  "Montclair State":"montclair.edu",
  "Moreno Valley":"mvc.edu",
  "Mount Mary":"mtmary.edu",
  "Mount Olive":"moc.edu",
  "Mount Saint Mary":"msmc.edu",
  "Mount St. Mary's":"msmary.edu",
  "Mount Union":"mountunion.edu",
  "Mt. San Jacinto":"msjc.edu",
  "Murray State":"mscok.edu",
  "NC State":"ncsu.edu",
  "Nassau CC":"ncc.edu",
  "Neumann":"neumann.edu",
  "Nevada":"unr.edu",
  "Nevada State":"nevadastate.edu",
  "New York University":"nyu.edu",
  "Newberry":"newberry.edu",
  "Niagara":"niagara.edu",
  "Norco":"norcocollege.edu",
  "Norfolk State":"nsu.edu",
  "North Alabama":"una.edu",
  "North Carolina A&T":"ncat.edu",
  "North Carolina Central":"nccu.edu",
  "North Central Missouri":"ncmissouri.edu",
  "North Florida":"unf.edu",
  "North Park":"northpark.edu",
  "Northwest Shoals CC":"nwscc.edu",
  "Northwestern Ohio":"northwesternohio.edu",
  "Northwestern-St. Paul":"unwsp.edu",
  "Nova Southeastern":"nova.edu",
  "Oklahoma":"ou.edu",
  "Oklahoma Wesleyan":"okwu.edu",
  "Old Dominion":"odu.edu",
  "Olivet Nazarene":"olivet.edu",
  "Ottawa":"ottawa.edu",
  "Our Lady of the Lake":"ollusa.edu",
  "Oxnard":"oxnardcollege.edu",
  "Palm Beach State":"palmbeachstate.edu",
  "Pasadena CC":"pasadena.edu",
  "Penn":"upenn.edu",
  "Penn State":"psu.edu",
  "Penn State Harrisburg":"harrisburg.psu.edu",
  "Penn State Schuylkill":"psu.edu",
  "PennWest California":"pennwest.edu",
  "Pittsburgh":"pitt.edu",
  "Plymouth State":"plymouth.edu",
  "Point":"point.edu",
  "Point Park":"pointpark.edu",
  "Post":"post.edu",
  "Prairie View A&M":"pvamu.edu",
  "Pratt CC":"prattcc.edu",
  "Princeton":"princeton.edu",
  "Purdue Fort Wayne":"pfw.edu",
  "Purdue Northwest":"pnw.edu",
  "RCSJ-Cumberland":"rcsj.edu",
  "RCSJ-Gloucester":"rcsj.edu",
  "Radford":"radford.edu",
  "Redlands":"redlands.edu",
  "Reedley":"reedleycollege.edu",
  "Reinhardt":"reinhardt.edu",
  "Richard Bland":"rbc.edu",
  "Ripon":"ripon.edu",
  "Roberts Wesleyan":"roberts.edu",
  "Rockford":"rockford.edu",
  "Rosemont":"rosemont.edu",
  "Roxbury CC":"rcc.mass.edu",
  "Russell Sage":"sage.edu",
  "Rutgers":"rutgers.edu",
  "SCAD Savannah":"scad.edu",
  "SUNY Brockport":"brockport.edu",
  "SUNY Cortland":"cortland.edu",
  "SUNY Geneseo":"geneseo.edu",
  "SUNY Old Westbury":"oldwestbury.edu",
  "Sacred Heart":"sacredheart.edu",
  "Saddleback":"saddleback.edu",
  "Saginaw Valley State":"svsu.edu",
  "Saint Benedict":"csbsju.edu",
  "Saint Francis":"sf.edu",
  "Saint Joseph's":"josephs.edu",
  "Saint Leo":"saintleo.edu",
  "Saint Mary":"stmary.edu",
  "Saint Mary's":"stmarys-ca.edu",
  "Saint Vincent":"vincent.edu",
  "Saint Xavier":"sxu.edu",
  "San Diego State":"sdsu.edu",
  "Santa Barbara CC":"sbcc.edu",
  "Santiago Canyon":"sccollege.edu",
  "Schreiner":"schreiner.edu",
  "Seton Hill":"setonhill.edu",
  "Shaw":"shawu.edu",
  "Shelton State CC":"sheltonstate.edu",
  "Shenandoah":"shenandoah.edu",
  "Simpson":"simpsonu.edu",
  "Slippery Rock":"slipperyrock.edu",
  "Snead State CC":"snead.edu",
  "South Florida":"usf.edu",
  "Southern New Orleans":"southernorleans.edu",
  "Southwestern":"swccd.edu",
  "Spelman":"spelman.edu",
  "Spring Hill":"shc.edu",
  "St. Catherine":"stkate.edu",
  "St. John Fisher":"sjf.edu",
  "St. Joseph's Brooklyn":"sjcny.edu",
  "St. Joseph's Long Island":"sjcny.edu",
  "St. Olaf":"stolaf.edu",
  "St. Thomas":"stu.edu",
  "St. Thomas Aquinas":"stac.edu",
  "Staten Island":"csi.cuny.edu",
  "Stillman":"stillman.edu",
  "Sweet Briar":"sbc.edu",
  "Syracuse":"syracuse.edu",
  "Talladega":"talladega.edu",
  "Tampa":"ut.edu",
  "Texas Southern":"tsu.edu",
  "Texas Wesleyan":"txwes.edu",
  "Thiel":"thiel.edu",
  "Thomas":"thomas.edu",
  "Thomas Jefferson":"thomasjefferson.edu",
  "Triton":"triton.edu",
  "UC Davis":"ucdavis.edu",
  "UC San Diego":"ucsd.edu",
  "UCF":"ucf.edu",
  "UCLA":"ucla.edu",
  "UConn":"uconn.edu",
  "UMBC":"umbc.edu",
  "UMass Dartmouth":"umassd.edu",
  "UNC Asheville":"unca.edu",
  "USC":"usc.edu",
  "USC Upstate":"uscupstate.edu",
  "UT Arlington":"uta.edu",
  "UT Southern":"utsouthern.edu",
  "Union":"union.edu",
  "Ursuline":"ursuline.edu",
  "Villa Maria":"vmc.edu",
  "Warner":"warner.edu",
  "Wesleyan":"wesleyancollege.edu",
  "Westcliff":"westcliff.edu",
  "William Penn":"wmpenn.edu",
  "William Woods":"williamwoods.edu",
  "Wisconsin-River Falls":"uwrf.edu"
};
